# Generated by Django 5.2.6 on 2025-10-09 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom de la salle ne doit contenir que des lettres et des chiffres', regex='^[a-zA-Z0-9\\s]+$')], verbose_name='Salle'),
        ),
    ]
