# Generated by Django 5.2.6 on 2025-10-09 13:56

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='paper',
            field=models.FileField(null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Article (PDF)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(help_text='Séparez les mots-clés par des virgules (max 10)', max_length=500, validators=[ConferenceApp.models.submission.validate_keywords], verbose_name='Mots-clés'),
        ),
    ]
