# Generated by Django 5.2.6 on 2025-10-09 13:56

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[UserApp.models.verify_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ce champ doit avoir des lettres et des espaces', regex='^[A-Za-z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ce champ doit avoir des lettres et des espaces', regex='^[A-Za-z\\s-]+$')]),
        ),
    ]
